### ISSUE TITLE
Make Site demo-able to put in portfolio

### ISSUE THREAD

**Issue by jwbw29** [jwbw29/smallgroup#35]
## Notes

- Find a way to create a demo-able site where there’s no login and test data
- maybe creating a separate vercel project that only deploys a specific branch, and then in that branch removing login stuff (or populating it with mock data so it still goes through the process), then having the data read from a local file

## Tasks
- [ ]  [[Read ChatGPT response](https://chat.openai.com/g/g-vSvzhUQDi-nextjs-app-router-gpt)](https://chat.openai.com/g/g-vSvzhUQDi-nextjs-app-router-gpt)
- [ ]  copy/paste/modify all the current page routes and components inside `/demo`
- [ ]  bypass the login and land straight at `/demo`
- [ ]  create `roster` and `events` test data
- [ ]  populate `/roster` and `/schedule` w/ testData
